### ISSUE TITLE
Ecobee changed their API to bearer token authentication

### ISSUE THREAD

**Issue by billykwooten** [rspier/go-ecobee#7]
Ecobee changes: https://www.ecobee.com/home/developer/api/documentation/v1/auth/developer-migration-summary.shtml

I noticed in the code we're calling an *http.client and then passing it into the GetThermostats function, however this isn't working anymore. We need to pass the bearer token (access token) into this call now for it to authenticate and be able to pull data from the API for the thermostats.

I'll take a stab at this later, we might have to create our own http.client vs pulling in the default one.

**Comment by rspier** [comment]
My existing token is working fine.  I can attempt to get a new token later and test.

IIRC, it should already be sending a `Bearer` header, via golang.org/x/oauth2.

My reading of the changes were that they were primarily around longer tokens and pins, not what was actually passed.

**Comment by rspier** [comment]
@billykwooten I've confirmed that it still works fine for `ecobee PIN` style authentication.    (I setup a new API key, ran through the whole process.)

Did you have it working for the other method before?   Can you share sample code?
